import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Mic,Square,Upload,Search,FileText,ListChecks,Clock,Trash2,Download,ShieldCheck,Play,Pause,Share2,Plus,Tag,Star,X}from'lucide-react';
import'./styles.css';
import'./mobile.css';

type TranscriptSegment={speaker:string;text:string;start:number;end:number};type ActionItem={task:string;owner?:string|null;due?:string|null;priority?:'low'|'medium'|'high'};type Meeting={id:string;title:string;date:string;duration:number;transcript:string;transcriptSegments?:TranscriptSegment[];speakerNames?:Record<string,string>;summary:string;actions:string[];actionDetails?:ActionItem[];keyPoints?:string[];decisions?:string[];topics?:string[];followUp?:string[];openQuestions?:string[];risks?:string[];meetingType?:string;language?:string;tags?:string[];completed?:boolean[];favorite?:boolean;audio?:string};
const seed:Meeting[]=[{id:'welcome',title:'Welcome to Meeting Notes',date:new Date().toISOString(),duration:0,language:'auto',transcript:'Record a meeting or import an audio file. Your recordings and notes stay on this device.',summary:'A private workspace for capturing meetings, transcripts, summaries, and action items.',actions:['Record your first meeting'],}];
const storeKey='meeting-notes-v1';
const load=():Meeting[]=>{try{return JSON.parse(localStorage.getItem(storeKey)||'null')||seed}catch{return seed}};
const summarize=(text:string)=>{const clean=(text.match(/[^.!?\n]+[.!?]?/g)||[]).map(s=>s.replace(/^\s*(speaker\s*\d+|[A-Z][a-z]+):\s*/i,'').trim()).filter(s=>s.length>2);if(!clean.length)return{summary:'No transcript is available yet.',actions:[]};const stop=new Set('the a an and or but to of in on for with is are was were be been it this that we i you they he she our your their from at as by about so just really have has had do did can could would'.split(' '));const freq=new Map<string,number>();clean.join(' ').toLowerCase().match(/[a-z][a-z\x27-]{2,}/g)?.forEach(w=>{if(!stop.has(w))freq.set(w,(freq.get(w)||0)+1)});const topics=[...freq.entries()].sort((a,b)=>b[1]-a[1]).slice(0,4).map(([w])=>w);const actionPattern=/\b(?:i|we|you|they|he|she|[A-Z][a-z]+)\s+(?:will|need(?:s)? to|should|must|plan(?:s)? to|agreed to|is going to|are going to)\b|^(?:please\s+)?(?:send|review|complete|schedule|confirm|check|update|create|prepare|call|email|share|follow up|finish|submit|assign|contact)\b|\b(?:due|deadline|by (?:monday|tuesday|wednesday|thursday|friday|saturday|sunday|tomorrow|next week|\w+ \d{1,2}))\b/i;const decisionPattern=/\b(decided|agreed|approved|selected|confirmed|finalized|will proceed|moving forward)\b/i;const actions=clean.filter(s=>actionPattern.test(s)).slice(0,8);const decisions=clean.filter(s=>decisionPattern.test(s)).slice(0,4);const scored=clean.map((s,i)=>({s,i,score:(s.toLowerCase().match(/[a-z][a-z\x27-]{2,}/g)||[]).reduce((n,w)=>n+(freq.get(w)||0),0)/Math.max(5,s.split(/\s+/).length)})).filter(x=>!actions.includes(x.s)).sort((a,b)=>b.score-a.score||a.i-b.i).slice(0,3).sort((a,b)=>a.i-b.i).map(x=>x.s);const parts=[`Overview: The meeting focused on ${topics.length?topics.join(', '):'the topics captured in the transcript'}.`,scored.length?`Key points:\n${scored.map(s=>'• '+s).join('\n')}`:'',decisions.length?`Decisions:\n${decisions.map(s=>'• '+s).join('\n')}`:'No explicit decisions were identified.',actions.length?`Follow-up: ${actions.length} action item${actions.length===1?'':'s'} identified.`:'No explicit follow-up assignments were identified.'];return{summary:parts.filter(Boolean).join('\n\n'),actions}};
const fmt=(s:number)=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;
const SB_URL='https://bazjlrualnmbanmhiuau.supabase.co';const SB_KEY='sb_publishable_ez3TVctnbFIUHqr_dMOUeQ_5WpsYEHs';type Session={access_token:string;refresh_token:string;user:{id:string;email?:string}};const sessionKey='meeting-notes-session';const loadSession=():Session|null=>{try{return JSON.parse(localStorage.getItem(sessionKey)||'null')}catch{return null}};

function App(){
 const[meetings,setMeetings]=useState<Meeting[]>(load);const[selected,setSelected]=useState(meetings[0]?.id||'');const[session,setSession]=useState<Session|null>(loadSession);const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[authMode,setAuthMode]=useState<'signin'|'signup'>('signin');const[cloudStatus,setCloudStatus]=useState('');const[recording,setRecording]=useState(false);const[paused,setPaused]=useState(false);const[consent,setConsent]=useState(false);const[language,setLanguage]=useState('auto');const[elapsed,setElapsed]=useState(0);const[live,setLive]=useState('');const[query,setQuery]=useState('');const[playing,setPlaying]=useState(false);const[processing,setProcessing]=useState('');const[error,setError]=useState('');const[question,setQuestion]=useState('');const[answer,setAnswer]=useState('');const media=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);const recognition=useRef<any>(null);const wakeLock=useRef<any>(null);const timer=useRef<number|undefined>();
 useEffect(()=>{localStorage.setItem(storeKey,JSON.stringify(meetings))},[meetings]);
 useEffect(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js')},[]);
 useEffect(()=>{session?localStorage.setItem(sessionKey,JSON.stringify(session)):localStorage.removeItem(sessionKey)},[session]);
 const current=meetings.find(m=>m.id===selected)||meetings[0];
 const filtered=useMemo(()=>meetings.filter(m=>(m.title+' '+m.transcript+' '+m.summary+' '+m.actions.join(' ')+' '+(m.tags||[]).join(' ')).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>Number(!!b.favorite)-Number(!!a.favorite)||+new Date(b.date)-+new Date(a.date)),[meetings,query]);
 async function start(){if(!consent){setError('Confirm that everyone has agreed to the recording.');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const mr=new MediaRecorder(stream);media.current=mr;mr.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data);const size=chunks.current.reduce((n,b)=>n+b.size,0);if(size>=23*1024*1024){setError('Recording stopped at the safe upload limit.');stop()}};mr.onerror=()=>stop();mr.start(1000);setLive('');setElapsed(0);setPaused(false);setRecording(true);try{wakeLock.current=await(navigator as any).wakeLock?.request('screen')}catch{}timer.current=window.setInterval(()=>setElapsed(v=>v+1),1000);await new Promise(requestAnimationFrame);const isiPhone=/iPhone|iPad|iPod/i.test(navigator.userAgent);const SR=!isiPhone&&((window as any).SpeechRecognition||(window as any).webkitSpeechRecognition);if(SR){try{const r=new SR();r.continuous=true;r.interimResults=true;r.onresult=(e:any)=>{let text='';for(let i=0;i<e.results.length;i++)text+=e.results[i][0].transcript+' ';setLive(text.trim())};r.onerror=()=>{};r.start();recognition.current=r}catch{recognition.current=null}}}catch{setRecording(false);alert('Microphone access is required to record a meeting.')}}
 async function analyzeMeeting(m:Meeting){setProcessing('Generating AI meeting notes…');const response=await fetch('/api/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:m.title,transcript:m.transcript,meetingType:m.meetingType||'general'})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Analysis failed');const updated={...m,summary:data.summary,actions:data.action_items.map((x:ActionItem)=>x.task),actionDetails:data.action_items,keyPoints:data.key_points,decisions:data.decisions,topics:data.topics,followUp:data.follow_up,openQuestions:data.open_questions,risks:data.risks};setMeetings(v=>v.map(x=>x.id===m.id?updated:x));return updated}
 async function processAudio(blob:Blob,m:Meeting){try{setError('');setProcessing('Transcribing recording…');const form=new FormData();form.append('audio',blob,`meeting.${blob.type.includes('mp4')?'mp4':'webm'}`);form.append('language',m.language||language);const response=await fetch('/api/transcribe',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error(data.error||'Transcription failed');const segments:TranscriptSegment[]=Array.isArray(data.segments)?data.segments.filter((x:any)=>x&&typeof x.text==='string').map((x:any)=>({speaker:String(x.speaker||'Speaker'),text:String(x.text),start:Number(x.start)||0,end:Number(x.end)||0})):[];const withTranscript={...m,transcript:data.transcript,transcriptSegments:segments,duration:m.duration||Math.round(Number(data.duration)||0)};setMeetings(v=>v.map(x=>x.id===m.id?withTranscript:x));await analyzeMeeting(withTranscript)}catch(e){setError(e instanceof Error?e.message:'AI processing failed')}finally{setProcessing('')}}
 function stop(){const mr=media.current;if(!mr){setRecording(false);return}const finish=()=>{const blob=new Blob(chunks.current,{type:mr.mimeType||'audio/webm'});const audio=blob.size?URL.createObjectURL(blob):undefined;const text=live.trim();const result=summarize(text);const m:Meeting={id:crypto.randomUUID(),title:`Meeting ${new Date().toLocaleDateString()}`,date:new Date().toISOString(),duration:elapsed,language,transcript:text||'Processing audio…',summary:text?result.summary:'Your AI summary will appear after transcription.',actions:result.actions,audio};setMeetings(v=>[m,...v]);setSelected(m.id);media.current=null;if(blob.size)void processAudio(blob,m)};mr.onstop=finish;try{if(mr.state!=='inactive')mr.stop();else finish()}catch{finish()}mr.stream.getTracks().forEach(t=>t.stop());try{recognition.current?.stop()}catch{}recognition.current=null;clearInterval(timer.current);try{wakeLock.current?.release()}catch{}wakeLock.current=null;setPaused(false);setRecording(false)}
 function pauseRecording(){const mr=media.current;if(!mr)return;try{if(mr.state==='recording'){mr.pause();setPaused(true);clearInterval(timer.current)}else if(mr.state==='paused'){mr.resume();setPaused(false);timer.current=window.setInterval(()=>setElapsed(v=>v+1),1000)}}catch{setError('Pause or resume is not supported on this browser.')}}
 function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;if(file.size>24*1024*1024){setError('Choose an audio file smaller than 24 MB.');return}const m:Meeting={id:crypto.randomUUID(),title:file.name.replace(/\.[^.]+$/,''),date:new Date().toISOString(),duration:0,transcript:'Processing audio…',summary:'Creating AI meeting notes…',actions:[],audio:URL.createObjectURL(file)};setMeetings(v=>[m,...v]);setSelected(m.id);void processAudio(file,m);e.target.value=''}
 async function authenticate(){try{setError('');setCloudStatus(authMode==='signup'?'Creating account…':'Signing in…');const path=authMode==='signup'?'/auth/v1/signup':'/auth/v1/token?grant_type=password';const response=await fetch(SB_URL+path,{method:'POST',headers:{apikey:SB_KEY,'content-type':'application/json'},body:JSON.stringify({email,password})});const data=await response.json();if(!response.ok)throw new Error(data.msg||data.error_description||'Sign-in failed');if(!data.access_token){setCloudStatus('Check your email to confirm your account, then sign in.');return}setSession(data);setPassword('');setCloudStatus('Signed in. Loading cloud meetings…');await loadCloud(data)}catch(e){setError(e instanceof Error?e.message:'Sign-in failed');setCloudStatus('')}}
 async function loadCloud(active=session){if(!active)return;try{setCloudStatus('Loading cloud meetings…');const response=await fetch(SB_URL+'/rest/v1/mn_meetings?select=*&order=created_at.desc',{headers:{apikey:SB_KEY,Authorization:'Bearer '+active.access_token}});const rows=await response.json();if(!response.ok)throw new Error(rows.message||'Cloud load failed');const cloud:Meeting[]=rows.map((r:any)=>({id:r.id,title:r.title,date:r.started_at||r.created_at,duration:r.duration_seconds,transcript:r.transcript,summary:r.summary,actions:r.metadata?.actions||[],actionDetails:r.metadata?.actionDetails||[],keyPoints:r.metadata?.keyPoints||[],decisions:r.decisions||[],topics:r.key_topics||[],followUp:r.follow_up_agenda||[],openQuestions:r.open_questions||[],risks:r.risks||[],meetingType:r.meeting_type||'general',language:r.language||'auto',tags:r.metadata?.tags||[],completed:r.metadata?.completed||[],favorite:!!r.metadata?.favorite,transcriptSegments:r.metadata?.transcriptSegments||[],speakerNames:r.metadata?.speakerNames||{}}));if(cloud.length){setMeetings(v=>{const map=new Map(v.map(x=>[x.id,x]));cloud.forEach(x=>map.set(x.id,x));return[...map.values()].sort((a,b)=>+new Date(b.date)-+new Date(a.date))});setSelected(cloud[0].id)}setCloudStatus('Cloud sync ready')}catch(e){setError(e instanceof Error?e.message:'Cloud load failed');setCloudStatus('')}}
 async function syncCloud(){if(!session)return;try{setCloudStatus('Syncing…');const valid=meetings.filter(m=>m.id!=='welcome');if(!valid.length){setCloudStatus('Nothing to sync yet');return}const rows=valid.map(m=>({id:m.id,user_id:session.user.id,title:m.title,meeting_type:m.meetingType||'general',status:'complete',language:m.language==='auto'?'en':m.language||'en',started_at:m.date,duration_seconds:m.duration,transcript:m.transcript,summary:m.summary,decisions:m.decisions||[],open_questions:m.openQuestions||[],risks:m.risks||[],follow_up_agenda:m.followUp||[],key_topics:m.topics||[],source:'pwa',metadata:{actions:m.actions,actionDetails:m.actionDetails,keyPoints:m.keyPoints,tags:m.tags||[],completed:m.completed||[],favorite:!!m.favorite,transcriptSegments:m.transcriptSegments||[],speakerNames:m.speakerNames||{}}}));const response=await fetch(SB_URL+'/rest/v1/mn_meetings?on_conflict=id',{method:'POST',headers:{apikey:SB_KEY,Authorization:'Bearer '+session.access_token,'content-type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify(rows)});if(!response.ok){const data=await response.json();throw new Error(data.message||'Sync failed')}setCloudStatus('Synced across devices')}catch(e){setError(e instanceof Error?e.message:'Sync failed');setCloudStatus('')}}
 function signOut(){setSession(null);setCloudStatus('');setPassword('')}
 function update(p:Partial<Meeting>){if(!current)return;setMeetings(v=>v.map(m=>m.id===current.id?{...m,...p}:m))}
 async function regenerate(){if(!current)return;try{setError('');await analyzeMeeting(current)}catch(e){setError(e instanceof Error?e.message:'Analysis failed');const r=summarize(current.transcript);update(r)}finally{setProcessing('')}}
 async function ask(){if(!current||!question.trim())return;try{setProcessing('Searching this meeting…');setError('');const response=await fetch('/api/ask',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question,transcript:current.transcript,summary:current.summary})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Question failed');setAnswer(data.answer)}catch(e){setError(e instanceof Error?e.message:'Question failed')}finally{setProcessing('')}}
 function renameSpeaker(speaker:string,name:string){if(!current)return;update({speakerNames:{...(current.speakerNames||{}),[speaker]:name}})}
 function addAction(){if(!current)return;update({actions:[...current.actions,'New action item'],completed:[...(current.completed||[]),false]})}
 function removeAction(i:number){if(!current)return;update({actions:current.actions.filter((_,n)=>n!==i),actionDetails:current.actionDetails?.filter((_,n)=>n!==i),completed:(current.completed||[]).filter((_,n)=>n!==i)})}
 function toggleAction(i:number){if(!current)return;const next=[...(current.completed||[])];next[i]=!next[i];update({completed:next})}
 function addTag(value:string){if(!current)return;const tag=value.trim().replace(/^#/,'');if(!tag)return;update({tags:[...new Set([...(current.tags||[]),tag])]})}
 async function shareMeeting(){if(!current)return;const text=`${current.title}\n\n${current.summary}\n\nAction items:\n${current.actions.map((x,i)=>`${current.completed?.[i]?'✓':'•'} ${x}`).join('\n')}`;try{if(navigator.share)await navigator.share({title:current.title,text});else{await navigator.clipboard.writeText(text);setCloudStatus('Meeting notes copied')}}catch{}}
 function remove(){if(!current||!confirm('Delete this meeting from this device?'))return;const next=meetings.filter(m=>m.id!==current.id);setMeetings(next);setSelected(next[0]?.id||'')}
 function download(){if(!current)return;const section=(name:string,items?:string[])=>items?.length?`\n\n${name.toUpperCase()}\n${items.map(x=>'• '+x).join('\n')}`:'';const body=`${current.title}\n${new Date(current.date).toLocaleString()}\nType: ${current.meetingType||'general'}\n\nSUMMARY\n${current.summary}${section('Key points',current.keyPoints)}${section('Decisions',current.decisions)}${section('Action items',current.actions)}${section('Open questions',current.openQuestions)}${section('Risks',current.risks)}${section('Follow-up agenda',current.followUp)}\n\nTRANSCRIPT\n${current.transcript}`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type:'text/plain'}));a.download=current.title+'.txt';a.click()}
 return <main>
  <aside><div className="brand"><span className="logo"><Mic/></span><div><b>Meeting Notes</b><small>Private workspace</small></div></div><div className="search"><Search/><input aria-label="Search meetings" placeholder="Search meetings" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="meeting-list">{filtered.map(m=><button className={m.id===selected?'active':''} onClick={()=>setSelected(m.id)} key={m.id}><span>{m.title}</span><small>{new Date(m.date).toLocaleDateString()} · {fmt(m.duration)}</small></button>)}</div><div className="cloud-auth">{session?<><small>{session.user.email}</small><button onClick={()=>void syncCloud()}>Sync now</button><button className="text-button" onClick={signOut}>Sign out</button>{cloudStatus&&<small>{cloudStatus}</small>}</>:<><b>Cloud sync</b><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={()=>void authenticate()} disabled={!email||password.length<8}>{authMode==='signup'?'Create account':'Sign in'}</button><button className="text-button" onClick={()=>setAuthMode(authMode==='signin'?'signup':'signin')}>{authMode==='signin'?'Create an account':'Already have an account'}</button>{cloudStatus&&<small>{cloudStatus}</small>}</>}</div><div className="privacy"><ShieldCheck/><span>{session?'Protected cloud sync enabled':'Stored only on this device'}</span></div></aside>
  <section className="workspace"><header><div>{current?<div className="title-row"><input className="title-input" aria-label="Meeting title" value={current.title} onChange={e=>update({title:e.target.value})}/><button className={current.favorite?'star active':'star'} aria-label="Favorite meeting" onClick={()=>update({favorite:!current.favorite})}><Star/></button></div>:<h1>New meeting</h1>}<p>{current?new Date(current.date).toLocaleString():'Start your first recording'}</p></div><div className="header-actions"><button className="ghost" onClick={()=>void shareMeeting()}><Share2/> Share</button><button className="ghost" onClick={download}><Download/> Export</button><button className="ghost danger" onClick={remove}><Trash2/></button></div></header>
   <div className="meeting-controls"><label>Meeting type<select value={current?.meetingType||'general'} onChange={e=>update({meetingType:e.target.value})}><option value="general">General</option><option value="one-on-one">1:1</option><option value="project">Project update</option><option value="client">Client meeting</option><option value="interview">Interview</option><option value="brainstorm">Brainstorm</option><option value="training">Training</option></select></label><label>Language<select value={language} onChange={e=>{setLanguage(e.target.value);if(current)update({language:e.target.value})}}><option value="auto">Auto detect</option><option value="en">English</option><option value="es">Spanish</option><option value="fr">French</option><option value="de">German</option><option value="pt">Portuguese</option><option value="it">Italian</option><option value="ja">Japanese</option><option value="ko">Korean</option><option value="zh">Chinese</option></select></label><span>AI tailors notes to this format.</span></div>
   <label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I confirmed that participants agreed to this recording.</span></label>
   <div className="recorder"><div className={`pulse ${recording?'on':''}`}><Mic/></div><div><b>{recording?'Listening…':'Ready to record'}</b><span>{recording?fmt(elapsed):'Capture audio and live transcript'}</span></div>{recording?<><button className="pause" onClick={pauseRecording}>{paused?<Play/>:<Pause/>} {paused?'Resume':'Pause'}</button><button className="stop" onClick={stop}><Square/> Stop</button></>:<button className="record" onClick={start} disabled={!consent}><Mic/> Record</button>}<label className="upload"><Upload/> Import<input type="file" accept="audio/*,video/*" onChange={upload}/></label></div>
   {recording&&<><div className="mobile-record-controls"><button onClick={pauseRecording}>{paused?<Play/>:<Pause/>} {paused?'Resume':'Pause'}</button><button className="mobile-stop" onClick={stop}><Square/> Stop recording · {fmt(elapsed)}</button></div><div className="live"><span>{paused?'RECORDING PAUSED':(/iPhone|iPad|iPod/i.test(navigator.userAgent)?'RECORDING AUDIO':'LIVE TRANSCRIPT')}</span><p>{live||(/iPhone|iPad|iPod/i.test(navigator.userAgent)?'Recording safely. Add or paste the transcript when you finish.':'Start speaking. Your transcript will appear here.')}</p></div></>}
   {processing&&<div className="status ai-status">{processing}</div>}{error&&<div className="status error-status">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
   {current&&<><div className="grid"><article><div className="section-title"><FileText/><h2>Summary</h2><button onClick={regenerate}>Generate summary</button></div><textarea aria-label="Meeting summary" value={current.summary} onChange={e=>update({summary:e.target.value})}/></article><article><div className="section-title"><ListChecks/><h2>Action items</h2><button onClick={addAction}><Plus/> Add</button></div><div className="actions">{current.actions.length?current.actions.map((a,i)=><label className={current.completed?.[i]?'done':''} key={i}><input type="checkbox" checked={!!current.completed?.[i]} onChange={()=>toggleAction(i)}/><span contentEditable suppressContentEditableWarning onBlur={e=>{const n=[...current.actions];n[i]=e.currentTarget.textContent||'';update({actions:n})}}>{a}{current.actionDetails?.[i]&&(current.actionDetails[i].owner||current.actionDetails[i].due)?<small>{[current.actionDetails[i].owner,current.actionDetails[i].due].filter(Boolean).join(' · ')}</small>:null}</span><button className="remove-action" aria-label="Remove action item" onClick={()=>removeAction(i)}><X/></button></label>):<span>No supported action items were identified.</span>}</div></article></div>
   <article className="organize"><div className="section-title"><Tag/><h2>Topics and tags</h2></div><div className="tag-list">{[...(current.topics||[]),...(current.tags||[])].filter((x,i,a)=>a.indexOf(x)===i).map((x,i)=><span key={i}>#{x}{current.tags?.includes(x)&&<button aria-label={"Remove "+x} onClick={()=>update({tags:current.tags?.filter(t=>t!==x)})}><X/></button>}</span>)}</div><form className="tag-form" onSubmit={e=>{e.preventDefault();const input=e.currentTarget.elements.namedItem('tag') as HTMLInputElement;addTag(input.value);input.value=''}}><input name="tag" placeholder="Add a tag"/><button>Add tag</button></form></article>
   {current.audio&&<div className="player"><button onClick={()=>{const el=document.querySelector('audio')!;playing?el.pause():el.play();setPlaying(!playing)}}>{playing?<Pause/>:<Play/>}</button><audio src={current.audio} onEnded={()=>setPlaying(false)}/><div><b>Meeting audio</b><span>Playback stored for this session</span></div></div>}
   {(current.keyPoints?.length||current.decisions?.length)&&<div className="grid insights"><article><div className="section-title"><FileText/><h2>Key points</h2></div><ul>{current.keyPoints?.map((x,i)=><li key={i}>{x}</li>)}</ul></article><article><div className="section-title"><ListChecks/><h2>Decisions</h2></div>{current.decisions?.length?<ul>{current.decisions.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p>No explicit decisions identified.</p>}</article></div>}
   {(current.openQuestions?.length||current.risks?.length||current.followUp?.length)&&<div className="intelligence-grid"><article><div className="section-title"><Search/><h2>Open questions</h2></div>{current.openQuestions?.length?<ul>{current.openQuestions.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p>None identified.</p>}</article><article><div className="section-title"><ShieldCheck/><h2>Risks</h2></div>{current.risks?.length?<ul>{current.risks.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p>None identified.</p>}</article><article><div className="section-title"><Clock/><h2>Next meeting</h2></div>{current.followUp?.length?<ul>{current.followUp.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p>No follow-up agenda needed.</p>}</article></div>}
   <article className="ask"><div className="section-title"><Search/><h2>Ask this meeting</h2></div><div className="ask-row"><input placeholder="What was decided? Who owns the follow-up?" value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void ask()}}/><button onClick={()=>void ask()} disabled={!question.trim()||!!processing}>Ask</button></div>{answer&&<p className="answer">{answer}</p>}</article>
   <article className="transcript"><div className="section-title"><Clock/><h2>Transcript</h2><span>{current.transcript.split(/\s+/).filter(Boolean).length} words</span></div>{current.transcriptSegments?.length?<details className="speaker-transcript" open><summary>Speaker timeline · {new Set(current.transcriptSegments.map(s=>s.speaker)).size} speakers</summary><div className="speaker-names">{[...new Set(current.transcriptSegments.map(s=>s.speaker))].map(speaker=><label key={speaker}><span>{speaker.replace(/_/g,' ')}</span><input aria-label={"Rename "+speaker} value={current.speakerNames?.[speaker]||''} placeholder={"Name "+speaker.replace(/_/g,' ')} onChange={e=>renameSpeaker(speaker,e.target.value)}/></label>)}</div><div className="speaker-segments">{current.transcriptSegments.map((segment,i)=><div className="speaker-segment" key={i}><b>{current.speakerNames?.[segment.speaker]?.trim()||segment.speaker.replace(/_/g,' ')}</b><time>{fmt(Math.round(segment.start))}</time><p>{segment.text}</p></div>)}</div></details>:null}<label className="editable-transcript"><span>{current.transcriptSegments?.length?'Editable transcript':'Meeting transcript'}</span><textarea aria-label="Meeting transcript" value={current.transcript} onChange={e=>update({transcript:e.target.value})}/></label></article></>}
  </section>
 </main>
}
createRoot(document.getElementById('root')!).render(<App/>);
