import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Mic,Square,Upload,Search,FileText,ListChecks,Clock,Trash2,Download,ShieldCheck,Play,Pause}from'lucide-react';
import'./styles.css';
import'./mobile.css';

type ActionItem={task:string;owner?:string|null;due?:string|null;priority?:'low'|'medium'|'high'};type Meeting={id:string;title:string;date:string;duration:number;transcript:string;summary:string;actions:string[];actionDetails?:ActionItem[];keyPoints?:string[];decisions?:string[];topics?:string[];followUp?:string[];audio?:string};
const seed:Meeting[]=[{id:'welcome',title:'Welcome to Meeting Notes',date:new Date().toISOString(),duration:0,transcript:'Record a meeting or import an audio file. Your recordings and notes stay on this device.',summary:'A private workspace for capturing meetings, transcripts, summaries, and action items.',actions:['Record your first meeting'],}];
const storeKey='meeting-notes-v1';
const load=():Meeting[]=>{try{return JSON.parse(localStorage.getItem(storeKey)||'null')||seed}catch{return seed}};
const summarize=(text:string)=>{const clean=(text.match(/[^.!?\n]+[.!?]?/g)||[]).map(s=>s.replace(/^\s*(speaker\s*\d+|[A-Z][a-z]+):\s*/i,'').trim()).filter(s=>s.length>2);if(!clean.length)return{summary:'No transcript is available yet.',actions:[]};const stop=new Set('the a an and or but to of in on for with is are was were be been it this that we i you they he she our your their from at as by about so just really have has had do did can could would'.split(' '));const freq=new Map<string,number>();clean.join(' ').toLowerCase().match(/[a-z][a-z\x27-]{2,}/g)?.forEach(w=>{if(!stop.has(w))freq.set(w,(freq.get(w)||0)+1)});const topics=[...freq.entries()].sort((a,b)=>b[1]-a[1]).slice(0,4).map(([w])=>w);const actionPattern=/\b(?:i|we|you|they|he|she|[A-Z][a-z]+)\s+(?:will|need(?:s)? to|should|must|plan(?:s)? to|agreed to|is going to|are going to)\b|^(?:please\s+)?(?:send|review|complete|schedule|confirm|check|update|create|prepare|call|email|share|follow up|finish|submit|assign|contact)\b|\b(?:due|deadline|by (?:monday|tuesday|wednesday|thursday|friday|saturday|sunday|tomorrow|next week|\w+ \d{1,2}))\b/i;const decisionPattern=/\b(decided|agreed|approved|selected|confirmed|finalized|will proceed|moving forward)\b/i;const actions=clean.filter(s=>actionPattern.test(s)).slice(0,8);const decisions=clean.filter(s=>decisionPattern.test(s)).slice(0,4);const scored=clean.map((s,i)=>({s,i,score:(s.toLowerCase().match(/[a-z][a-z\x27-]{2,}/g)||[]).reduce((n,w)=>n+(freq.get(w)||0),0)/Math.max(5,s.split(/\s+/).length)})).filter(x=>!actions.includes(x.s)).sort((a,b)=>b.score-a.score||a.i-b.i).slice(0,3).sort((a,b)=>a.i-b.i).map(x=>x.s);const parts=[`Overview: The meeting focused on ${topics.length?topics.join(', '):'the topics captured in the transcript'}.`,scored.length?`Key points:\n${scored.map(s=>'• '+s).join('\n')}`:'',decisions.length?`Decisions:\n${decisions.map(s=>'• '+s).join('\n')}`:'No explicit decisions were identified.',actions.length?`Follow-up: ${actions.length} action item${actions.length===1?'':'s'} identified.`:'No explicit follow-up assignments were identified.'];return{summary:parts.filter(Boolean).join('\n\n'),actions}};
const fmt=(s:number)=>`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`;

function App(){
 const[meetings,setMeetings]=useState<Meeting[]>(load);const[selected,setSelected]=useState(meetings[0]?.id||'');const[recording,setRecording]=useState(false);const[elapsed,setElapsed]=useState(0);const[live,setLive]=useState('');const[query,setQuery]=useState('');const[playing,setPlaying]=useState(false);const[processing,setProcessing]=useState('');const[error,setError]=useState('');const[question,setQuestion]=useState('');const[answer,setAnswer]=useState('');const media=useRef<MediaRecorder|null>(null);const chunks=useRef<Blob[]>([]);const recognition=useRef<any>(null);const timer=useRef<number|undefined>();
 useEffect(()=>{localStorage.setItem(storeKey,JSON.stringify(meetings))},[meetings]);
 useEffect(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js')},[]);
 const current=meetings.find(m=>m.id===selected)||meetings[0];
 const filtered=useMemo(()=>meetings.filter(m=>(m.title+' '+m.transcript).toLowerCase().includes(query.toLowerCase())),[meetings,query]);
 async function start(){try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const mr=new MediaRecorder(stream);media.current=mr;mr.ondataavailable=e=>chunks.current.push(e.data);mr.onerror=()=>stop();mr.start(1000);setLive('');setElapsed(0);setRecording(true);timer.current=window.setInterval(()=>setElapsed(v=>v+1),1000);await new Promise(requestAnimationFrame);const isiPhone=/iPhone|iPad|iPod/i.test(navigator.userAgent);const SR=!isiPhone&&((window as any).SpeechRecognition||(window as any).webkitSpeechRecognition);if(SR){try{const r=new SR();r.continuous=true;r.interimResults=true;r.onresult=(e:any)=>{let text='';for(let i=0;i<e.results.length;i++)text+=e.results[i][0].transcript+' ';setLive(text.trim())};r.onerror=()=>{};r.start();recognition.current=r}catch{recognition.current=null}}}catch{setRecording(false);alert('Microphone access is required to record a meeting.')}}
 async function analyzeMeeting(m:Meeting){setProcessing('Generating AI meeting notes…');const response=await fetch('/api/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:m.title,transcript:m.transcript})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Analysis failed');const updated={...m,summary:data.summary,actions:data.action_items.map((x:ActionItem)=>x.task),actionDetails:data.action_items,keyPoints:data.key_points,decisions:data.decisions,topics:data.topics,followUp:data.follow_up};setMeetings(v=>v.map(x=>x.id===m.id?updated:x));return updated}
 async function processAudio(blob:Blob,m:Meeting){try{setError('');setProcessing('Transcribing recording…');const form=new FormData();form.append('audio',blob,`meeting.${blob.type.includes('mp4')?'mp4':'webm'}`);const response=await fetch('/api/transcribe',{method:'POST',body:form});const data=await response.json();if(!response.ok)throw new Error(data.error||'Transcription failed');const withTranscript={...m,transcript:data.transcript};setMeetings(v=>v.map(x=>x.id===m.id?withTranscript:x));await analyzeMeeting(withTranscript)}catch(e){setError(e instanceof Error?e.message:'AI processing failed')}finally{setProcessing('')}}
 function stop(){const mr=media.current;if(!mr){setRecording(false);return}const finish=()=>{const blob=new Blob(chunks.current,{type:mr.mimeType||'audio/webm'});const audio=blob.size?URL.createObjectURL(blob):undefined;const text=live.trim();const result=summarize(text);const m:Meeting={id:crypto.randomUUID(),title:`Meeting ${new Date().toLocaleDateString()}`,date:new Date().toISOString(),duration:elapsed,transcript:text||'Processing audio…',summary:text?result.summary:'Your AI summary will appear after transcription.',actions:result.actions,audio};setMeetings(v=>[m,...v]);setSelected(m.id);media.current=null;if(blob.size)void processAudio(blob,m)};mr.onstop=finish;try{if(mr.state!=='inactive')mr.stop();else finish()}catch{finish()}mr.stream.getTracks().forEach(t=>t.stop());try{recognition.current?.stop()}catch{}recognition.current=null;clearInterval(timer.current);setRecording(false)}
 function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;if(file.size>24*1024*1024){setError('Choose an audio file smaller than 24 MB.');return}const m:Meeting={id:crypto.randomUUID(),title:file.name.replace(/\.[^.]+$/,''),date:new Date().toISOString(),duration:0,transcript:'Processing audio…',summary:'Creating AI meeting notes…',actions:[],audio:URL.createObjectURL(file)};setMeetings(v=>[m,...v]);setSelected(m.id);void processAudio(file,m);e.target.value=''}
 function update(p:Partial<Meeting>){if(!current)return;setMeetings(v=>v.map(m=>m.id===current.id?{...m,...p}:m))}
 async function regenerate(){if(!current)return;try{setError('');await analyzeMeeting(current)}catch(e){setError(e instanceof Error?e.message:'Analysis failed');const r=summarize(current.transcript);update(r)}finally{setProcessing('')}}
 async function ask(){if(!current||!question.trim())return;try{setProcessing('Searching this meeting…');setError('');const response=await fetch('/api/ask',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question,transcript:current.transcript,summary:current.summary})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Question failed');setAnswer(data.answer)}catch(e){setError(e instanceof Error?e.message:'Question failed')}finally{setProcessing('')}}
 function remove(){if(!current||!confirm('Delete this meeting from this device?'))return;const next=meetings.filter(m=>m.id!==current.id);setMeetings(next);setSelected(next[0]?.id||'')}
 function download(){if(!current)return;const body=`${current.title}\n${new Date(current.date).toLocaleString()}\n\nSUMMARY\n${current.summary}\n\nACTION ITEMS\n${current.actions.map(x=>'• '+x).join('\n')}\n\nTRANSCRIPT\n${current.transcript}`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type:'text/plain'}));a.download=current.title+'.txt';a.click()}
 return <main>
  <aside><div className="brand"><span className="logo"><Mic/></span><div><b>Meeting Notes</b><small>Private workspace</small></div></div><div className="search"><Search/><input aria-label="Search meetings" placeholder="Search meetings" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="meeting-list">{filtered.map(m=><button className={m.id===selected?'active':''} onClick={()=>setSelected(m.id)} key={m.id}><span>{m.title}</span><small>{new Date(m.date).toLocaleDateString()} · {fmt(m.duration)}</small></button>)}</div><div className="privacy"><ShieldCheck/><span>Stored only on this device</span></div></aside>
  <section className="workspace"><header><div><h1>{current?.title||'New meeting'}</h1><p>{current?new Date(current.date).toLocaleString():'Start your first recording'}</p></div><div className="header-actions"><button className="ghost" onClick={download}><Download/> Export</button><button className="ghost danger" onClick={remove}><Trash2/></button></div></header>
   <div className="recorder"><div className={`pulse ${recording?'on':''}`}><Mic/></div><div><b>{recording?'Listening…':'Ready to record'}</b><span>{recording?fmt(elapsed):'Capture audio and live transcript'}</span></div>{recording?<button className="stop" onClick={stop}><Square/> Stop</button>:<button className="record" onClick={start}><Mic/> Record</button>}<label className="upload"><Upload/> Import<input type="file" accept="audio/*,video/*" onChange={upload}/></label></div>
   {recording&&<><button className="mobile-stop" onClick={stop}><Square/> Stop recording · {fmt(elapsed)}</button><div className="live"><span>{/iPhone|iPad|iPod/i.test(navigator.userAgent)?'RECORDING AUDIO':'LIVE TRANSCRIPT'}</span><p>{live||(/iPhone|iPad|iPod/i.test(navigator.userAgent)?'Recording safely. Add or paste the transcript when you finish.':'Start speaking. Your transcript will appear here.')}</p></div></>}
   {processing&&<div className="status ai-status">{processing}</div>}{error&&<div className="status error-status">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
   {current&&<><div className="grid"><article><div className="section-title"><FileText/><h2>Summary</h2><button onClick={regenerate}>Generate summary</button></div><textarea aria-label="Meeting summary" value={current.summary} onChange={e=>update({summary:e.target.value})}/></article><article><div className="section-title"><ListChecks/><h2>Action items</h2></div><div className="actions">{current.actions.length?current.actions.map((a,i)=><label key={i}><input type="checkbox"/><span contentEditable suppressContentEditableWarning onBlur={e=>{const n=[...current.actions];n[i]=e.currentTarget.textContent||'';update({actions:n})}}>{a}{current.actionDetails?.[i]&&(current.actionDetails[i].owner||current.actionDetails[i].due)?<small>{[current.actionDetails[i].owner,current.actionDetails[i].due].filter(Boolean).join(' · ')}</small>:null}</span></label>):<span>No supported action items were identified.</span>}</div></article></div>
   {current.audio&&<div className="player"><button onClick={()=>{const el=document.querySelector('audio')!;playing?el.pause():el.play();setPlaying(!playing)}}>{playing?<Pause/>:<Play/>}</button><audio src={current.audio} onEnded={()=>setPlaying(false)}/><div><b>Meeting audio</b><span>Playback stored for this session</span></div></div>}
   {(current.keyPoints?.length||current.decisions?.length)&&<div className="grid insights"><article><div className="section-title"><FileText/><h2>Key points</h2></div><ul>{current.keyPoints?.map((x,i)=><li key={i}>{x}</li>)}</ul></article><article><div className="section-title"><ListChecks/><h2>Decisions</h2></div>{current.decisions?.length?<ul>{current.decisions.map((x,i)=><li key={i}>{x}</li>)}</ul>:<p>No explicit decisions identified.</p>}</article></div>}
   <article className="ask"><div className="section-title"><Search/><h2>Ask this meeting</h2></div><div className="ask-row"><input placeholder="What was decided? Who owns the follow-up?" value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void ask()}}/><button onClick={()=>void ask()} disabled={!question.trim()||!!processing}>Ask</button></div>{answer&&<p className="answer">{answer}</p>}</article>
   <article className="transcript"><div className="section-title"><Clock/><h2>Transcript</h2><span>{current.transcript.split(/\s+/).filter(Boolean).length} words</span></div><textarea aria-label="Meeting transcript" value={current.transcript} onChange={e=>update({transcript:e.target.value})}/></article></>}
  </section>
 </main>
}
createRoot(document.getElementById('root')!).render(<App/>);
